### PR TITLE
add srv and msg for naoqi_apps/launch/locomotionControl.launch

### PR DESCRIPTION
**Pull request by kochigami**
These are msgs and srvs for locomotion control APIs in `ALMotion` (https://github.com/ros-naoqi/naoqi_bridge/pull/61)
1. srv/MoveIsActive.srv  : for `moveIsActive`
2. srv/GetArmsEnabled.srv: for `getMoveArmsEnabled`
3. msg/Arms.msg in #19 is required for #14 (getMoveArmsEnabled).
4. srv/GetRobotVelocity.srv: for `getRobotVelocity`
5. srv/GetRobotPosition.srv for `getRobotPosition`
6. srv/GetNextRobotPosition.srv: for `getNextRobotPosition`

If there is any problem, please let me know.

### CODE REVIEW

**Comment by kochigami** [comment]
I also added msgs and srv for `getMoveConfig`in http://doc.aldebaran.com/2-4/naoqi/motion/control-walk-api.html#control-walk-api
However, I only tested on Pepper, I'm not sure yet what happens when I tried it on Nao.
- MoveConfigNames.msg
- MoveConfig.msg
- GetMoveConfig.srv

If there is any problem, please let me know.

**Comment by suryaambrose** [comment]
Hi, 

As for #19, I have an issue with one of the message and Nao. Sorry :(

In the documentation, moveConfig is described as follows:
[ ["MaxStepX", value],
  ["MaxStepY", value],
  ["MaxStepTheta", value],
  ["MaxStepFrequency", value],
  ["StepHeight", value],
  ["TorsoWx", value],
  ["TorsoWy", value]
]

This fits with what I can see on my Nao, but not with your moveConfig.msg key names, which seems to be closer from this type of message (that I got on a Pepper with most recent dev version) :
[ ["MaxVelXY", value],
  ["MaxVelTheta", value],
  ["MaxAccXY", value],
  ["MaxAccTheta", value],
  ["MaxJerkXY", value],
  ["MaxJerkTheta", value],
  ["TorsoWy", value]
]

All the rest seems to work (or at least, it is consistent with Nao). Maybe the part related to moveConfig can be removed from this PR until we find a proper way to handle the Nao/Pepper difference ?

**Comment by Karsten1987** [comment]
What's the status on this?

**Comment by kochigami** [comment]
This is an old pull-request.
This may cause unexpected trouble when it is merged.
I close this and improve this in my local.
I'm sorry to leave this for a long time.

**Pull request closed without merging**
