### PR TITLE
add ShowImage srv file for ALTabletService.showImage

### PR DESCRIPTION
**Pull request by kochigami**
I added the service file for ALTabletService/showImage.
What I am thinking is that 
1. sending the picture name by using this file, 
2. and then `naoqi_apps/nodes/naoqi_tablet.py`  (I will send another pull-request later) adds it to the url of the picture and executes `showImage`. 

If there is any problem, please let me know. 
Thank you for any help you can provide.

### CODE REVIEW

**Comment by vrabaud** [comment]
wouldn't you want a status value ? (e.g., what if the file does not exist)

**Comment by kochigami** [comment]
Thank you very much for your advice.
I added a status value by using `std_msgs/Bool` .
If the result of `ShowImage` fails (= the file does not exist), it returns False.
On the other hand, if the function succeeds, it returns True.

**Comment by suryaambrose** [comment]
LGTM

**Comment by kochigami** [comment]
I added `ShowApp.srv` and `ShowWebview.srv`. 
These structures are almost same as `ShowImage.srv`. 

If there is any problem, please let me know.

**Comment by vrabaud** [comment]
Those messages are the same, maybe you want to combine them into one ? Like ShowResource or something. Also, please add comments on what the service actually does and what each parameter is (the string is what ? a URI ? ). For the status, please keep the convention from: http://docs.ros.org/api/std_srvs/html/srv/Trigger.html

**Comment by kochigami** [comment]
Thank you very much for your comment.
I modified srv file and summarized my changes.

| service name | what parameter "name" of ShowResource.srv requires | documentation | example |
| :-: | :-: | :-: | :-: |
| show_image | picture name (ex. pepper.jpg) | Aldebaran 2.4.2.26 documentation -> ALTabletService ->  showImage | rosservice call /show_image "name: data: 'penguin_shitamuki.jpg'" success: data: True |
| show_app | app name (ex. j-browser-tablet) | Aldebaran 2.4.2.26 documentation -> ALTabletService ->  loadApplication, showWebview | rosservice call /show_app "name: data: 'j-tablet-browser'" success: data: True |
| show_webview | website url (ex. https: //www.aldebaran.com/ja) | Aldebaran 2.4.2.26 documentation -> ALTabletService ->  loadUrl, showWebview | rosservice call /show_webview "name: data: 'https://www .aldebaran.com/ja'"  success: data: True |

**Comment by kochigami** [comment]
- delete `ShowResource.srv` because it can be replaced by `SetString.srv`.
- add `ConfigureWifi.srv` 
ref: http://doc.aldebaran.com/2-4/naoqi/core/altabletservice-api.html#altabletservice-api => `configureWifi`

**Comment by kochigami** [comment]
This is a new feature, which may cause unexpected trouble when it is merged.
I close this and improve this in my local.
I'm sorry to leave this for a long time.

**Pull request closed without merging**
