### PR TITLE
add HandTouch.msg for hand touch detection

### PR DESCRIPTION
**Pull request by kochigami**
I added HandTouch.msg, by following Bumper.msg.
Even though there are six events related to hand touch (
`HandRightBackTouched`, `HandRightLeftTouched`, `HandRightRightTouched`,
`HandLeftBackTouched`, `HandLeftLeftTouched`, `HandLeftRightTouched`), I just prepare for the message that tells which hand is touched. 

If there is any problem, please let me know.

### CODE REVIEW

**Comment by vrabaud** [comment]
Could you actually please change the const to be capital letters like indicated here: http://wiki.ros.org/msg#Constants. Thx
(we should also change the BUmper.msg but we are not for legacy reasons)

**Comment by kochigami** [comment]
I fixed it, but I am not sure if I should also change `stateReleased=0`, `statePressed=1`.
I am sorry for troubling you. Please let me know if there is any problem.

**Comment by vrabaud** [comment]
well, let's keep stateReleased for now, just for coherence with Bumper. Thx !

**Comment by suryaambrose** [comment]
Hi, 

Arriving really really late, would it be possible to rename TactileTouch in HeadTouch then ? It would seem more consistent to me.

**Comment by kochigami** [comment]
Thank you very much for your comment.
I'll send a pull request about renaming it after merging https://github.com/ros-naoqi/naoqi_driver/pull/63 .

**Pull request merged**
